title: "Pham Doan Tan Phat"
name: "Pham Doan Tan Phat"
description: "Sinh vien IOT - PTIT"
url: "https://tanph4t.github.io"

author:
  name: "Pham Doan Tan Phat"
  bio: "Sinh vien PTIT"
  location: "TP. Ho Chi Minh"
  email: "pdtanphat3805@gmail.com"
  github: "tanph4t"